internal/counter: fix TestNewFile test
The test checks whether a newly created counter file has
the TimeEnd metadata value within expected range, by computing
the time difference between the TimeEnd value and a test reference
time computed at the beginning of the test.
Unfortunately, the reference timestamp calculation used a different
time zone than what's used in computing TimeEnd, and caused the
test failure on some builders with some probabilities depending on
builders' time zones.

Here is the log from the test failure that shows this issue.


--- FAIL: TestNewFile (0.00s)
    counter_test.go:177: GOOS linux GOARCH amd64
    counter_test.go:233: now: 2023-07-08 00:00:00 +0000 UTC file: counter.test-go1.19.10-linux-amd64-2023-07-08.v1.count TimeBegin: 2023-07-08 00:00:00 +0800 CST TimeEnd: 2023-07-16 00:00:00 +0800 CST
    counter_test.go:234: 0: days = 7, want 7 < days <= 14
    counter_test.go:233: now: 2023-07-08 00:00:00 +0000 UTC file: counter.test-go1.19.10-linux-amd64-2023-07-08.v1.count TimeBegin: 2023-07-08 00:00:00 +0800 CST TimeEnd: 2023-07-16 00:00:00 +0800 CST
    counter_test.go:234: 13: days = 7, want 7 < days <= 14
    counter_test.go:233: now: 2023-07-08 00:00:00 +0000 UTC file: counter.test-go1.19.10-linux-amd64-2023-07-08.v1.count TimeBegin: 2023-07-08 00:00:00 +0800 CST TimeEnd: 2023-07-16 00:00:00 +0800 CST
    counter_test.go:234: 15: days = 7, want 7 < days <= 14

For golang/go#60970
Fixes golang/go#60966

Change-Id: I52936f5fe12c13f7ccf3c052cbbb9b403fcad332
Reviewed-on: https://go-review.googlesource.com/c/telemetry/+/508501
Run-TryBot: Hyang-Ah Hana Kim <hyangah@gmail.com>
Reviewed-by: Peter Weinberger <pjw@google.com>
Run-TryBot: Heschi Kreinick <heschi@google.com>
TryBot-Result: Gopher Robot <gobot@golang.org>