internal/content/telemetrygodev: handle missing null program charts
Fixes the following exception during rendering:

TypeError: t.Charts is not iterable
    at charts.ts:40:33
    at charts.ts:155:1

When there is no data, the worker produces programs like:

Programs: [
  {Charts: null, ID: 'charts:cmd/compile', Name: 'cmd/compile'},
  ...
]

Change-Id: Ifb01e46a6bae51253b150668d1cfd657eaa04a90
Reviewed-on: https://go-review.googlesource.com/c/telemetry/+/592395
Reviewed-by: Robert Findley <rfindley@google.com>
LUCI-TryBot-Result: Go LUCI <golang-scoped@luci-project-accounts.iam.gserviceaccount.com>